#!/bin/sh
# SPDX-License-Identifier: MIT
set -eu

cargo fmt --all -- --check
cargo clippy --all-targets --all-features --locked -- -D warnings
cargo test --all-targets --all-features --locked
cargo build --release --locked
